export default [
  {
    id: "9582",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898886/g0x2cwcmy5oyda4snlcd.png",
    parent: "Drinks",
    children: ["Tea", "Water", "Juice", "Coffee", "Energy Drinks"],
    type: "Grocery",
  },
  {
    id: "957C",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899603/z7jq5afzk5jivyy9ejx2.png",
    parent: "Snacks & Instant",
    children: ["Tea", "Water", "Juice"],
    type: "Grocery",
  },
  {
    id: "9576",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899837/hitatjdxe3ldcfhcxpdg.png",
    parent: "Sports & Fitness",
    children: ["Tea", "Water", "Juice", "Coffee", "Energy Drinks"],
    type: "Sports & Fitness",
  },
  {
    id: "9584",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898463/rdehnuh4ormxuclahm7k.png",
    parent: "Cooking Essentials",
    children: ["Oil", "Rice", "Flour", "Dry Vegetable", "Spices & Mixes"],
    type: "Grocery",
  },
  {
    id: "9580",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898293/hzq6zcatoouos47tm2ej.png",
    parent: "Organic Food",
    children: ["Organic Food"],
    type: "Grocery",
  },
  {
    id: "9580",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898146/aolu4dryjfofkmvxhtac.png",
    parent: "Fish & Meat",
    children: ["Fish", "Meat"],
    type: "Grocery",
  },
  {
    id: "9587",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898282/fq1hjkheem3e0xrgpwjs.png",
    parent: "Fruits & Vegetable",
    children: ["Dry Fruits", "Fresh Fruits", "Fresh Vegetable"],
    type: "Grocery",
  },
  {
    id: "9586",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898071/sctbjvub5tunzmo64j9l.png",
    parent: "Biscuits & Cakes",
    children: ["Cakes", "Biscuits"],
    type: "Grocery",
  },
  {
    id: "9585",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898921/fbbtcof0be7eygids9z5.png",
    parent: "Fresh Seafood",
    children: ["Fresh Seafood"],
    type: "Grocery",
  },
  {
    id: "9583",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898729/riqv3im6voejh3li1avx.png",
    parent: "Breakfast",
    children: ["Bread,", "Cereal"],
    type: "Grocery",
  },
  {
    id: "9578",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899743/qzjzrf8r49upcdsggpda.png",
    parent: "Pet Care",
    children: ["Cat Care,", "Dog Care", "Bird Care"],
    type: "Grocery",
  },
  {
    id: "9577",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899846/zbp6thbnznsnp9077yeb.png",
    parent: "Beauty & Health",
    children: [
      "Bath",
      "Cosmetics",
      "Oral Care",
      "Skin Care",
      "Body Care",
      "Shaving Needs",
    ],
    type: "Health Care",
  },
  {
    id: "9581",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643898980/xe2za8mpmtgisb1lbdhq.png",
    parent: "Milk & Dairy",
    children: ["Dairy", "Ice Cream", "Butter & Ghee"],
    type: "Grocery",
  },
  {
    id: "957E",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899099/nw2kunc8puqoaxpzu9qa.png",
    parent: "Sauces & Pickles",
    children: ["Sauces", "Pickles & Condiments"],
    type: "Grocery",
  },
  {
    id: "957D",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899172/av8fh9xt5aq4ne9hedut.png",
    parent: "Jam & Jelly",
    children: ["Jam & Jelly"],
    type: "Grocery",
  },
  {
    id: "957A",
    icon: "https://res.cloudinary.com/ahossain/image/upload/v1643899700/mtoxrvix2asxbdtic2pz.png",
    parent: "Household Tools",
    children: [
      "Cleaner",
      "Laundry",
      "Air Freshener",
      "Water Filter",
      "Pest Control",
      "Cleaning Tools",
    ],
    type: "Home Accessories",
  },
];
