export default [
  {
    id: "33BA",
    startDate: "Aug 15, 2021",
    endDate: "Aug 31, 2021",
    campaignsName: "August Gift Voucher",
    code: "AUGUST21",
    percentage: "20%",
    productType: "Grocery",
    status: "Expired",
  },
  {
    id: "33BA",
    startDate: "Aug 15, 2021",
    endDate: "Aug 31, 2021",
    campaignsName: "August Gift Voucher",
    code: "AUGUST21",
    percentage: "20%",
    productType: "Grocery",
    status: "Expired",
  },
  {
    id: "33D4",
    startDate: "Aug 20, 2021",
    endDate: "Aug 31, 2021",
    campaignsName: "Winter Gift Voucher",
    code: "WINTER21",
    percentage: "12%",
    productType: "Cloths",
    status: "Expired",
  },
  {
    id: "33E3",
    startDate: "Aug 13, 2021",
    endDate: "Aug 31, 2021",
    campaignsName: "Summer Gift Voucher",
    code: "SUMMER21",
    percentage: "15%",
    productType: "Grocery",
    status: "Expired",
  },
  {
    id: "ABFE",
    startDate: "Aug 20, 2021",
    endDate: "Aug 31, 2021",
    campaignsName: "October Gift Voucher",
    code: "BLACKFRIDAY21",
    percentage: "10%",
    productType: "Grocery",
    status: "Expired",
  },
];
